---
- name: Install Dependencies
  ansible.builtin.apt:
    update_cache: true
    state: latest
    pkg:
      - libssl-dev
      - openssl
      - libnss3-dev
      - libkrb5-dev
      - libgmp-dev
      - zlib1g-dev
      - libbz2-dev
  become: true

- name: Download Source
  git:
    repo: https://github.com/openwall/john.git
    dest: /tools/passwords/johnj

- name: Configure
  command: sh ./configure
  args:
    chdir: /tools/passwords/johnj/src

- name: Make
  community.general.make:
    chdir: /tools/passwords/johnj/src
    target: install
    jobs: 4
    params: 
      -s:
  become: true