---
# https://waylonwalker.com/install-rust/
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists

- name: Download Installer
  when: cargo_exists.rc != "0"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rust.sh
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists.rc != "0"
  shell: /tmp/rust.sh -y
  tags:
    - rust
  become: true

